[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["gcc", "python311", "python311Packages.pip"] 