# Generated by Django 5.2 on 2025-04-18 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='assistant',
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ai_consultations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentconsultation',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultation', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentconsultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_doctor_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentconsultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_doctor_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentconsultation',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_consultations', to='api.scan'),
        ),
        migrations.DeleteModel(
            name='Assistant',
        ),
    ]
