# Generated by Django 5.2 on 2025-04-19 12:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_consultation_assistant_consultation_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='follow_up_required',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='recommendations',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency')], default='initial', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='api.scan'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('general', 'General Medicine'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology')], default='general', max_length=50)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_days', models.JSONField(default=list)),
                ('available_hours', models.JSONField(default=dict)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_consultations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-years_of_experience'],
            },
        ),
    ]
