# Generated by Django 5.2 on 2025-04-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentconsultation',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_hours',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(default='Experienced medical professional dedicated to patient care.'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('radiology', 'Radiology'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('dermatology', 'Dermatology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('general', 'General Medicine')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
