# Generated by Django 5.2 on 2025-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_appointmentconsultation_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_affiliations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_accepting_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='publications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('general', 'General Medicine'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('psychiatry', 'Psychiatry'), ('gynecology', 'Gynecology'), ('urology', 'Urology')], default='general', max_length=50),
        ),
    ]
