# Generated by Django 5.2 on 2025-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_doctor_age_doctor_awards_doctor_education_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='is_accepting_patients',
            new_name='is_accepting_new_patients',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_affiliations',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='research_interests',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken, comma separated', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('general', 'General Medicine'), ('pulmonology', 'Pulmonology'), ('radiology', 'Radiology')], default='general', max_length=50),
        ),
    ]
