# Generated by Django 5.2 on 2025-04-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_is_accepting_patients_doctor_is_accepting_new_patients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='appointment',
        ),
    ]
