# Generated by Django 5.2 on 2025-04-22 21:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_consultation_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.clean_media_path),
        ),
        migrations.DeleteModel(
            name='AppointmentConsultation',
        ),
    ]
