# Generated by Django 5.2 on 2025-04-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_doctor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
