# Generated by Django 5.2 on 2025-04-26 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_consultation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='XRayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xray_images/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_images', to='api.appointment')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_xray_images', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xray_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
