# Generated by Django 5.2 on 2025-05-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_appointment_status_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('scan', 'Scan'), ('payment', 'Payment'), ('system', 'System'), ('xray', 'X-Ray')], default='system', max_length=20),
        ),
    ]
