# Generated by Django 5.2 on 2025-05-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_doctor_availability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken, comma separated', max_length=200, null=True),
        ),
    ]
